# Generated by Django 6.1 on 2026-09-27 04:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0021_repuesto_codigo_sunat_unidadmedida_codigo_sunat'),
        ('ventas', '0019_backfill_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('01', 'Factura Electrónica'), ('03', 'Boleta de Venta Electrónica'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('09', 'Guía de Remisión Remitente')], db_index=True, max_length=2)),
                ('serie', models.CharField(db_index=True, max_length=10)),
                ('numero', models.CharField(db_index=True, max_length=15)),
                ('motivo_codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('cliente_tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=3)),
                ('cliente_documento', models.CharField(blank=True, default='', max_length=15)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de Envío'), ('ENVIADO', 'Enviado (procesando)'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado por SUNAT'), ('OBSERVADO', 'Observado por SUNAT'), ('ERROR_CONEXION', 'Error de Conexión'), ('BAJA_SOLICITADA', 'Baja Solicitada'), ('BAJA_ACEPTADA', 'Anulado (Baja Aceptada)')], db_index=True, default='PENDIENTE_ENVIO', max_length=20)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta_api', models.JSONField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, default='')),
                ('pdf_url', models.CharField(blank=True, default='', max_length=500)),
                ('xml_url', models.CharField(blank=True, default='', max_length=500)),
                ('cdr_url', models.CharField(blank=True, default='', max_length=500)),
                ('hash_cdr', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_sunat', models.CharField(blank=True, default='', help_text='Ticket para consultar el resultado asíncrono de una Comunicación de Baja.', max_length=100)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comprobante_relacionado', models.ForeignKey(blank=True, help_text='Comprobante original al que afecta esta nota de crédito/débito.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notas_generadas', to='facturacion.comprobanteelectronico')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comprobantes_electronicos_creados', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_electronicos_enviados', to=settings.AUTH_USER_MODEL)),
                ('guia_remision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comprobantes_electronicos', to='inventario.guiaremision')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comprobantes_electronicos', to='inventario.sucursal')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comprobantes_electronicos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'db_table': 'facturacion_comprobante_electronico',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteElectronicoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('codigo_sunat', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_unidad', models.CharField(blank=True, default='NIU', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_igv_codigo', models.CharField(default='10', max_length=2)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.comprobanteelectronico')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante Electrónico',
                'verbose_name_plural': 'Detalles de Comprobante Electrónico',
                'db_table': 'facturacion_comprobante_detalle',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteEnvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta_api', models.JSONField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='facturacion.comprobanteelectronico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_comprobante_electronico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Envío',
                'verbose_name_plural': 'Registros de Envío',
                'db_table': 'facturacion_comprobante_envio_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='comprobanteelectronico',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'serie', 'numero'), name='comprobante_electronico_unico_tipo_serie_numero'),
        ),
        migrations.AddConstraint(
            model_name='comprobanteelectronicodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='comprobante_detalle_cantidad_positiva'),
        ),
    ]
