# Generated by Django 6.1 on 2026-08-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_alter_inventariostock_stock_disponible_and_more'),
        ('vehiculos', '0003_add_kilometraje_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('RECEPCIONADO', 'Recepcionado'), ('INSPECCION', 'En Inspección'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('APROBADO', 'Aprobado / En Ejecución'), ('FINALIZADO', 'Finalizado'), ('FACTURADO', 'Facturado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RECEPCIONADO', max_length=30)),
                ('tipo_servicio', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('AMBOS', 'Preventivo y Correctivo')], default='PREVENTIVO', max_length=20)),
                ('kilometraje_ingreso', models.IntegerField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField(blank=True, help_text='Motivo principal o correctivo reportado por el cliente', null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('url_cotizacion_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_recepcionadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_trabajo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'taller_orden_trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aprobado_cliente', models.BooleanField(db_index=True, default=False)),
                ('completado', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Servicio de OT',
                'verbose_name_plural': 'Servicios de OT',
                'db_table': 'taller_orden_servicio',
            },
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aprobado_cliente', models.BooleanField(db_index=True, default=False)),
                ('entregado_por_almacen', models.BooleanField(default=False)),
                ('instalado', models.BooleanField(default=False)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.repuesto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Repuesto de OT',
                'verbose_name_plural': 'Repuestos de OT',
                'db_table': 'taller_orden_repuesto',
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'db_table': 'taller_hallazgo',
            },
        ),
    ]
