# Generated by Django 6.1 on 2026-08-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_estimado_minutos', models.IntegerField(blank=True, help_text='Tiempo aproximado que toma el servicio', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Plantilla Preventiva',
                'verbose_name_plural': 'Plantillas Preventivas',
                'db_table': 'taller_plantilla_preventiva',
                'ordering': ['nombre'],
            },
        ),
    ]
