# Generated by Django 6.1 on 2026-09-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('taller', '0002_plantillapreventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_trabajo', to='clientes.cliente'),
        ),
    ]
