# Generated by Django 6.1 on 2026-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_ordentrabajo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_vencimiento_cotizacion',
            field=models.DateTimeField(blank=True, help_text='Nivel transaccional: Fecha límite para que el cliente apruebe la cotización.', null=True),
        ),
    ]
