# Generated by Django 6.1 on 2026-09-03 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_ordentrabajo_fecha_vencimiento_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'taller_tipo_servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='tipo_servicio',
            new_name='tipo_servicio_legacy',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='taller.tiposervicio'),
        ),
    ]
