# Generated by Django 6.1 on 2026-09-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_tiposervicio_ordentrabajo_tipo_servicio_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tipo_servicio_legacy',
        ),
    ]
