# Generated by Django 6.1 on 2026-09-03 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_remove_ordentrabajo_tipo_servicio_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECEPCIONADO', 'Recepcionado'), ('INSPECCION', 'En Inspección'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('APROBADO', 'Aprobado / En Ejecución'), ('FINALIZADO', 'Finalizado'), ('FACTURADO', 'Facturado'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='taller.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'taller_orden_historial_estado',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
