# Generated by Django 6.1 on 2026-09-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_ordenhistorialestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
