# Generated by Django 6.1 on 2026-09-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_ordentrabajo_numero_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenhistorialestado',
            name='motivo_categoria',
            field=models.CharField(blank=True, choices=[('RECHAZO_CLIENTE', 'Cliente rechazó la cotización'), ('ERROR_REGISTRO', 'Error en el registro'), ('DUPLICADO', 'Orden duplicada'), ('OTRO', 'Otro motivo')], max_length=30, null=True),
        ),
    ]
