# Generated by Django 6.1 on 2026-09-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_ordenhistorialestado_motivo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='hallazgo_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_generados', to='taller.hallazgo'),
        ),
    ]
