# Generated by Codex on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        ('inventario', '0024_alter_aplicacionrepuesto_marca_vehiculo'),
        ('taller', '0012_add_plantilla_correctiva'),
        ('vehiculos', '0005_vehiculo_tipo_combustible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fecha_inicio', models.DateTimeField(db_index=True)),
                ('fecha_fin', models.DateTimeField(db_index=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('origen', models.CharField(choices=[('LLAMADA', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('PORTAL', 'Portal'), ('PRESENCIAL', 'Presencial'), ('OTRO', 'Otro')], db_index=True, default='LLAMADA', max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('RECEPCIONADA', 'Recepcionada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], db_index=True, default='CONFIRMADA', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones_cliente', models.TextField(blank=True, null=True)),
                ('observaciones_internas', models.TextField(blank=True, null=True)),
                ('kilometraje_estimado', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_registradas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('mecanico_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_preferidas', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='taller.ordentrabajo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='inventario.sucursal')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='taller.tiposervicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'taller_cita',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['sucursal', 'fecha_inicio'], name='idx_cita_sucursal_inicio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='idx_cita_estado_inicio'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_minutos__gt', 0)), name='cita_duracion_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='cita_fecha_fin_mayor_inicio'),
        ),
    ]
