# Generated by Codex on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_configuracion_default(apps, schema_editor):
    Sucursal = apps.get_model('inventario', 'Sucursal')
    ConfiguracionAgendaSucursal = apps.get_model('taller', 'ConfiguracionAgendaSucursal')
    HorarioAgendaSucursal = apps.get_model('taller', 'HorarioAgendaSucursal')

    for sucursal in Sucursal.objects.filter(estado=True):
        config, _ = ConfiguracionAgendaSucursal.objects.get_or_create(
            sucursal=sucursal,
            defaults={
                'intervalo_minutos': 30,
                'capacidad_simultanea': 3,
                'activo': True,
            },
        )
        existentes = set(config.horarios.values_list('dia_semana', flat=True))
        horarios = []
        for dia in range(7):
            if dia not in existentes:
                horarios.append(HorarioAgendaSucursal(
                    configuracion=config,
                    dia_semana=dia,
                    hora_inicio='08:00',
                    hora_fin='18:00',
                    cerrado=(dia == 6),
                ))
        if horarios:
            HorarioAgendaSucursal.objects.bulk_create(horarios)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_aplicacionrepuesto_marca_vehiculo'),
        ('taller', '0013_cita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgendaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30)),
                ('capacidad_simultanea', models.PositiveIntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_agenda', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Configuracion de Agenda por Sucursal',
                'verbose_name_plural': 'Configuraciones de Agenda por Sucursal',
                'db_table': 'taller_configuracion_agenda_sucursal',
            },
        ),
        migrations.CreateModel(
            name='BloqueoAgendaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(db_index=True)),
                ('fecha_fin', models.DateTimeField(db_index=True)),
                ('motivo', models.CharField(max_length=180)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Bloqueo de Agenda',
                'verbose_name_plural': 'Bloqueos de Agenda',
                'db_table': 'taller_bloqueo_agenda_sucursal',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAgendaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(default='08:00')),
                ('hora_fin', models.TimeField(default='18:00')),
                ('cerrado', models.BooleanField(default=False)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='taller.configuracionagendasucursal')),
            ],
            options={
                'verbose_name': 'Horario de Agenda',
                'verbose_name_plural': 'Horarios de Agenda',
                'db_table': 'taller_horario_agenda_sucursal',
                'ordering': ['dia_semana'],
                'unique_together': {('configuracion', 'dia_semana')},
            },
        ),
        migrations.AddConstraint(
            model_name='configuracionagendasucursal',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_minutos__gt', 0)), name='agenda_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='configuracionagendasucursal',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_simultanea__gt', 0)), name='agenda_capacidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='bloqueoagendasucursal',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='bloqueo_agenda_fin_mayor_inicio'),
        ),
        migrations.AddConstraint(
            model_name='horarioagendasucursal',
            constraint=models.CheckConstraint(condition=models.Q(('cerrado', True), _connector='OR') | models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='agenda_horario_fin_mayor_inicio_o_cerrado'),
        ),
        migrations.RunPython(crear_configuracion_default, migrations.RunPython.noop),
    ]
