# Generated by Django 6.1 on 2026-10-02 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_configuracion_agenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('REPROGRAMACION', 'Reprogramacion'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('RECEPCION', 'Recepcion'), ('CANCELACION', 'Cancelacion'), ('NO_ASISTIO', 'No asistio')], db_index=True, max_length=30)),
                ('estado_anterior', models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('RECEPCIONADA', 'Recepcionada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('RECEPCIONADA', 'Recepcionada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], max_length=20, null=True)),
                ('fecha_inicio_anterior', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_nueva', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='taller.cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cita',
                'verbose_name_plural': 'Historial de Citas',
                'db_table': 'taller_cita_historial',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cita', '-fecha'], name='idx_cita_historial_fecha')],
            },
        ),
    ]
