# Generated by Django 6.1 on 2026-10-02 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        ('inventario', '0024_alter_aplicacionrepuesto_marca_vehiculo'),
        ('taller', '0015_citahistorial'),
        ('vehiculos', '0005_vehiculo_tipo_combustible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEsperaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(db_index=True, max_length=15)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(blank=True, default='', max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('placa', models.CharField(db_index=True, max_length=15)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_preferida', models.DateField(db_index=True)),
                ('hora_preferida', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CONVERTIDO', 'Convertido a cita'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('observaciones_internas', models.TextField(blank=True, null=True)),
                ('creado_desde_portal', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita_convertida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_lista_espera', to='taller.cita')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lista_espera_citas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lista_espera_citas', to='inventario.sucursal')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lista_espera_citas', to='taller.tiposervicio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lista_espera_citas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Lista de Espera de Cita',
                'verbose_name_plural': 'Lista de Espera de Citas',
                'db_table': 'taller_lista_espera_cita',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['sucursal', 'estado', 'fecha_preferida'], name='idx_lista_espera_sucursal')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duracion_minutos__gt', 0)), name='lista_espera_duracion_positiva')],
            },
        ),
    ]
