# Generated by Django 6.1 on 2026-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='RUC', max_length=3)),
                ('numero_documento', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre_o_razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('licencia_conducir', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria_licencia', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportista',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-id'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
