# Generated by Django 6.1 on 2026-09-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_transportista_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
