# Generated by Django 6.1 on 2026-08-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Repuesto',
                'verbose_name_plural': 'Categorias de Repuestos',
                'db_table': 'categoria_repuesto',
            },
        ),
        migrations.CreateModel(
            name='MarcaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de Repuesto',
                'verbose_name_plural': 'Marcas de Repuestos',
                'db_table': 'marca_repuesto',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_por_mayor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='repuestos', to='inventario.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='repuestos', to='inventario.marcarepuesto')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuesto',
            },
        ),
        migrations.CreateModel(
            name='AplicacionRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_vehiculo', models.CharField(db_index=True, max_length=100)),
                ('modelo_vehiculo', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Aplicacion de Repuesto',
                'verbose_name_plural': 'Aplicaciones de Repuestos',
                'db_table': 'aplicacion_repuesto',
            },
        ),
    ]
