# Generated by Django 6.1 on 2026-08-20 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='almacenes', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
                'unique_together': {('sucursal', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('pasillo', models.CharField(blank=True, max_length=20, null=True)),
                ('estante', models.CharField(blank=True, max_length=20, null=True)),
                ('casillero', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ubicaciones', to='inventario.almacen')),
            ],
            options={
                'verbose_name': 'Ubicacion Fisica',
                'verbose_name_plural': 'Ubicaciones Fisicas',
                'db_table': 'ubicacion_fisica',
                'unique_together': {('almacen', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASLADO_ENTRADA', 'Traslado Entrada'), ('TRASLADO_SALIDA', 'Traslado Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('RESERVA', 'Reserva'), ('LIBERACION_RESERVA', 'Liberación de Reserva'), ('MERMA', 'Merma'), ('INVENTARIO_INICIAL', 'Inventario Inicial')], db_index=True, max_length=30)),
                ('cantidad', models.IntegerField()),
                ('stock_resultante', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.repuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.ubicacionfisica')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['repuesto', '-fecha'], name='idx_movimiento_repuesto_fecha'), models.Index(fields=['ubicacion', '-fecha'], name='idx_movimiento_ubicacion_fecha')],
            },
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.IntegerField(default=0)),
                ('stock_reservado', models.IntegerField(default=0)),
                ('stock_merma', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventario_stock', to='inventario.repuesto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventario_stock', to='inventario.ubicacionfisica')),
            ],
            options={
                'verbose_name': 'Inventario Stock',
                'verbose_name_plural': 'Inventario Stocks',
                'db_table': 'inventario_stock',
                'indexes': [models.Index(fields=['repuesto', 'ubicacion'], name='idx_stock_repuesto_ubicacion')],
                'unique_together': {('repuesto', 'ubicacion')},
            },
        ),
    ]
