# Generated by Django 6.1 on 2026-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariostock',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
