# Generated by Django 6.1 on 2026-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_inventariostock_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
