# Generated by Django 6.1 on 2026-08-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_almacen_direccion'),
        ('ventas', '0002_alter_venta_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='tipo_igv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repuestos', to='ventas.impuesto'),
        ),
    ]
