# Generated by Django 6.1 on 2026-08-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_repuesto_tipo_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionrepuesto',
            name='anio_desde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacionrepuesto',
            name='anio_hasta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
