# Generated by Django 6.1 on 2026-08-30 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_add_anio_desde_hasta_aplicacion_repuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=10)),
                ('permite_decimales', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.AddField(
            model_name='repuesto',
            name='es_granel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='viscosidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repuestos', to='inventario.unidadmedida'),
        ),
    ]
