# Generated by Django 6.1 on 2026-08-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_unidadmedida_repuesto_es_granel_repuesto_viscosidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='stock',
        ),
    ]
