# Generated by Django 6.1 on 2026-08-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_repuesto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_merma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_reservado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
