# Generated by Django 6.1 on 2026-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventariostock_stock_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='margen_minimo_esperado',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Margen mínimo esperado en porcentaje (ej. 20.00 para 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='alerta_precio',
            field=models.BooleanField(default=False, help_text='Se marca automáticamente si el margen cae por debajo del mínimo de la categoría al registrar una compra'),
        ),
    ]
