# Generated by Django 6.1 on 2026-09-07 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_categoria_margen_minimo_esperado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traslado', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='COMPLETADO', max_length=20)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_destino', to='inventario.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_origen', to='inventario.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado de Inventario',
                'verbose_name_plural': 'Traslados de Inventario',
                'db_table': 'traslado_inventario',
                'ordering': ['-fecha_traslado'],
            },
        ),
        migrations.CreateModel(
            name='TrasladoInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_detalle', to='inventario.repuesto')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.trasladoinventario')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_traslado_destino', to='inventario.ubicacionfisica')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_traslado_origen', to='inventario.ubicacionfisica')),
            ],
            options={
                'verbose_name': 'Detalle de Traslado',
                'verbose_name_plural': 'Detalles de Traslado',
                'db_table': 'traslado_inventario_detalle',
            },
        ),
    ]
