# Generated by Django 6.1 on 2026-09-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_transportista_alter_proveedor_options'),
        ('inventario', '0012_trasladoinventario_trasladoinventariodetalle'),
        ('seguridad', '0007_empresa_dias_validez_cotizacion'),
        ('vehiculos', '0004_vehiculotransporte'),
        ('ventas', '0013_alter_seriedocumentointerno_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(default=0)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_traslado', models.DateField()),
                ('punto_partida', models.CharField(max_length=255)),
                ('punto_llegada', models.CharField(max_length=255)),
                ('motivo_traslado', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('EN_TRASLADO', 'En Traslado'), ('COMPLETADA', 'Completada')], default='CREADA', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ventas.seriedocumentointerno')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guias_remision', to='inventario.sucursal')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.transportista')),
                ('ubigeo_llegada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guias_llegada', to='seguridad.distrito')),
                ('ubigeo_partida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guias_partida', to='seguridad.distrito')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vehiculos.vehiculotransporte')),
            ],
            options={
                'verbose_name': 'Guía de Remisión',
                'verbose_name_plural': 'Guías de Remisión',
                'db_table': 'inventario_guia_remision',
            },
        ),
        migrations.CreateModel(
            name='GuiaRemisionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.guiaremision')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Guía de Remisión',
                'verbose_name_plural': 'Detalles de Guía de Remisión',
                'db_table': 'inventario_guia_remision_detalle',
            },
        ),
    ]
