# Generated by Django 6.1 on 2026-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_guiaremision_guiaremisiondetalle'),
        ('ventas', '0014_cajas_extend_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guiaremisiondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='guia_remision_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='inventariostock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__gte', 0)), name='inventario_stock_disponible_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='inventariostock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_merma__gte', 0)), name='inventario_stock_merma_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_compra__gte', 0)), name='repuesto_precio_compra_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_por_mayor__gte', 0)), name='repuesto_precio_por_mayor_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_cash__gte', 0)), name='repuesto_precio_cash_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_lista__gte', 0)), name='repuesto_precio_lista_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='trasladoinventariodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='traslado_detalle_cantidad_positiva'),
        ),
    ]
