# Generated by Django 6.1 on 2026-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_guiaremisiondetalle_guia_remision_detalle_cantidad_positiva_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventariostock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reservado__gte', 0)), name='inventario_stock_reservado_no_negativo'),
        ),
    ]
