# Generated by Django 6.1 on 2026-09-12 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_inventariostock_inventario_stock_reservado_no_negativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladoinventario',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoinventario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
