# Generated by Django 6.1 on 2026-09-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_trasladoinventario_confirmado_por_and_more'),
        ('ventas', '0016_alter_seriedocumentointerno_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladoinventario',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ventas.seriedocumentointerno'),
        ),
    ]
