# Generated by Codex on 2026-09-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0017_kioskoterminal_venta_kiosko'),
        ('inventario', '0017_trasladoinventario_correlativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='guias_remision_origen', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='guias_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='observacion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='venta_generada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guia_remision_origen', to='ventas.venta'),
        ),
    ]
