# Generated by Codex on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_mejorar_flujo_guias_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaremision',
            name='estado',
            field=models.CharField(
                choices=[
                    ('CREADA', 'Creada'),
                    ('LISTA_PARA_SALIDA', 'Lista para Salida'),
                    ('EN_TRASLADO', 'En Traslado'),
                    ('COMPLETADA', 'Completada'),
                    ('FACTURADA', 'Facturada'),
                ],
                default='CREADA',
                max_length=20,
            ),
        ),
    ]
