# Generated by Codex on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_guiaremision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barra',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
