# Generated by Django 6.1 on 2026-09-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_repuesto_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='codigo_sunat',
            field=models.CharField(blank=True, help_text='Código de clasificación SUNAT (UNSPSC) requerido para emitir comprobantes electrónicos.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='codigo_sunat',
            field=models.CharField(blank=True, help_text='Código de unidad de medida SUNAT (catálogo 03), ej: NIU, KGM.', max_length=10, null=True),
        ),
    ]
