# Generated by Django 6.1 on 2026-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_repuesto_codigo_sunat_unidadmedida_codigo_sunat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionrepuesto',
            name='motor',
        ),
        migrations.AddField(
            model_name='aplicacionrepuesto',
            name='tipo_combustible',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'Gasolinero'), ('PETROLEO', 'Petrolero')], max_length=10, null=True),
        ),
    ]
