# Generated by Codex on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_remove_aplicacionrepuesto_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='visible_en_kiosko',
            field=models.BooleanField(
                default=False,
                help_text='Define si este repuesto se muestra en el catalogo publico del kiosko.',
            ),
        ),
    ]
