# Generated by Django 6.1 on 2026-09-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_repuesto_visible_en_kiosko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacionrepuesto',
            name='marca_vehiculo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
