# Generated by Django 6.1 on 2026-09-05 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_transportista_alter_proveedor_options'),
        ('inventario', '0011_categoria_margen_minimo_esperado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(db_index=True)),
                ('tipo_comprobante', models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta'), ('Guia', 'Guía de Remisión'), ('Ticket', 'Ticket')], max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('numero_comprobante', models.CharField(db_index=True, max_length=20)),
                ('tipo_pago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito')], default='Contado', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Completada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='clientes.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Pago Parcial'), ('Pagada', 'Pagada')], db_index=True, default='Pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='compras.compra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentas_por_pagar', to='clientes.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'db_table': 'cuenta_por_pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Costo unitario de compra', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_compra', to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='PagoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(db_index=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, help_text='Nro de operación, etc.', max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.cuentaporpagar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Cuenta por Pagar',
                'verbose_name_plural': 'Pagos de Cuentas por Pagar',
                'db_table': 'pago_cuenta_por_pagar',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
