# Generated by Django 6.1 on 2026-09-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobanteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado_activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante de Compra',
                'verbose_name_plural': 'Tipos de Comprobantes de Compras',
                'db_table': 'tipo_comprobante_compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_comprobante',
            field=models.CharField(blank=True, choices=[('Factura', 'Factura'), ('Boleta', 'Boleta'), ('Guia', 'Guía de Remisión'), ('Ticket', 'Ticket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_comprobante_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='compras.tipocomprobantecompra'),
        ),
    ]
