# Generated by Django 6.1 on 2026-09-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_tipocomprobantecompra_alter_compra_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='tipo_comprobante',
        ),
    ]
