# Generated by Django 6.1 on 2026-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_compra_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Pago Parcial'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
