# Generated by Django 6.1 on 2026-09-12 05:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_cuentaporpagar_estado'),
        ('ventas', '0016_alter_seriedocumentointerno_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuenta',
            name='afecta_caja',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagocuenta',
            name='movimiento_caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pago_cuenta_rel', to='ventas.movimientocaja'),
        ),
        migrations.AlterField(
            model_name='pagocuenta',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='pagocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('monto_abonado__gt', 0)), name='pago_cuenta_monto_positivo'),
        ),
    ]
