# Generated by Django 6.1 on 2026-10-09 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CITA', 'Recordatorio de cita'), ('VEHICULO_LISTO', 'Vehículo listo'), ('COTIZACION', 'Cotización por vencer'), ('MANTENIMIENTO', 'Mantenimiento próximo'), ('DOCUMENTO', 'Documento por vencer'), ('CUOTA', 'Cobranza de cuota')], db_index=True, max_length=20)),
                ('referencia', models.CharField(max_length=120)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, default='', help_text='Solo dígitos, con código de país (51...).', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_evento', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('descartado_automatico', models.BooleanField(default=False)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Aviso a cliente',
                'verbose_name_plural': 'Avisos a clientes',
                'db_table': 'aviso_cliente',
                'ordering': ['fecha_evento', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'referencia'), name='aviso_unico_por_hecho')],
            },
        ),
    ]
