# Generated by Django 6.1 on 2026-10-08 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        ('inventario', '0024_alter_aplicacionrepuesto_marca_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de herramienta',
                'verbose_name_plural': 'Categorías de herramientas',
                'db_table': 'herramientas_categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('numero_serie', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('estado_operativo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADA', 'Asignada'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('EN_REPARACION', 'En reparación'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('PERDIDA', 'Perdida'), ('DADA_DE_BAJA', 'Dada de baja')], db_index=True, default='DISPONIBLE', max_length=20)),
                ('estado_fisico', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='NUEVO', max_length=10)),
                ('potencia', models.CharField(blank=True, default='', max_length=50)),
                ('voltaje', models.CharField(blank=True, default='', max_length=50)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('horas_uso_acumuladas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas', to='inventario.almacen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas', to='herramientas.categoriaherramienta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas', to='clientes.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'herramientas_herramienta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA', 'Baja del registro')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='herramientas.herramienta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historial_herramientas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de herramienta',
                'verbose_name_plural': 'Historial de herramientas',
                'db_table': 'herramientas_historial',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['sucursal', 'estado_operativo'], name='herramienta_sucursa_aaeac3_idx'),
        ),
        migrations.AddConstraint(
            model_name='herramienta',
            constraint=models.CheckConstraint(condition=models.Q(('horas_uso_acumuladas__gte', 0)), name='herramienta_horas_no_negativas'),
        ),
    ]
