# Generated by Django 6.1 on 2026-10-08 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialherramienta',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA', 'Baja del registro'), ('ENTREGA', 'Entrega a técnico'), ('DEVOLUCION', 'Devolución'), ('ANULACION_ASIGNACION', 'Asignación anulada')], max_length=25),
        ),
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('DEVUELTA', 'Devuelta'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=10)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado_fisico_entrega', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=10)),
                ('estado_fisico_devolucion', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='', max_length=10)),
                ('horas_uso_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones_entrega', models.TextField(blank=True, default='')),
                ('observaciones_devolucion', models.TextField(blank=True, default='')),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas_entregadas', to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='herramientas.herramienta')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='herramientas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de herramienta',
                'verbose_name_plural': 'Asignaciones de herramientas',
                'db_table': 'herramientas_asignacion',
                'ordering': ['-fecha_entrega', '-id'],
                'indexes': [models.Index(fields=['tecnico', 'estado'], name='herramienta_tecnico_322e3a_idx'), models.Index(fields=['herramienta', 'estado'], name='herramienta_herrami_c5096c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('herramienta',), name='asignacion_unica_activa_por_herramienta'), models.CheckConstraint(condition=models.Q(('horas_uso_periodo__gte', 0)), name='asignacion_horas_no_negativas')],
            },
        ),
    ]
