# Generated by Django 6.1 on 2026-10-08 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_alter_historialherramienta_accion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionherramienta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('DEVUELTA', 'Devuelta'), ('ANULADA', 'Anulada'), ('NO_DEVUELTA', 'No devuelta (robo o pérdida)')], db_index=True, default='ACTIVA', max_length=12),
        ),
        migrations.AlterField(
            model_name='historialherramienta',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA', 'Baja del registro'), ('ENTREGA', 'Entrega a técnico'), ('DEVOLUCION', 'Devolución'), ('ANULACION_ASIGNACION', 'Asignación anulada'), ('MANTENIMIENTO_INICIO', 'Inicio de mantenimiento'), ('MANTENIMIENTO_FIN', 'Fin de mantenimiento'), ('INCIDENCIA', 'Incidencia')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlanMantenimientoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CALIBRACION', 'Calibración'), ('LIMPIEZA', 'Limpieza'), ('CAMBIO_PIEZAS', 'Cambio de piezas (discos, carbones, etc.)'), ('OTRO', 'Otro')], default='PREVENTIVO', max_length=15)),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultima_fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('ultimas_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proxima_fecha', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('proximas_horas', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='planes_herramienta_creados', to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='planes_mantenimiento', to='herramientas.herramienta')),
            ],
            options={
                'verbose_name': 'Plan de mantenimiento',
                'verbose_name_plural': 'Planes de mantenimiento',
                'db_table': 'herramientas_plan_mantenimiento',
                'ordering': ['proxima_fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo (reparación)')], max_length=12)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EN_CURSO', max_length=12)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('realizado_por', models.CharField(blank=True, default='', max_length=150)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('repuestos_usados', models.TextField(blank=True, default='')),
                ('resultado', models.TextField(blank=True, default='')),
                ('horas_herramienta_al_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, default='', max_length=255)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos', to='herramientas.herramienta')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='registros', to='herramientas.planmantenimientoherramienta')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'db_table': 'herramientas_mantenimiento',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DANO', 'Daño'), ('ROBO', 'Robo'), ('PERDIDA', 'Pérdida'), ('OTRO', 'Otro')], max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('RESUELTA', 'Resuelta')], db_index=True, default='ABIERTA', max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision', models.CharField(blank=True, choices=[('REPARAR', 'Reparar'), ('DAR_DE_BAJA', 'Dar de baja'), ('REPONER', 'Reponer (comprar otra)'), ('SIN_ACCION', 'Sin acción')], default='', max_length=12)),
                ('notas_resolucion', models.TextField(blank=True, default='')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias', to='herramientas.herramienta')),
                ('reportada_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias_como_responsable', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia de herramienta',
                'verbose_name_plural': 'Incidencias de herramientas',
                'db_table': 'herramientas_incidencia',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['herramienta', 'estado'], name='herramienta_herrami_5c7821_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='planmantenimientoherramienta',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_dias__isnull', False), ('intervalo_horas__isnull', False), _connector='OR'), name='plan_requiere_algun_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='planmantenimientoherramienta',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_dias__isnull', True), ('intervalo_dias__gt', 0), _connector='OR'), name='plan_intervalo_dias_positivo'),
        ),
        migrations.AddConstraint(
            model_name='planmantenimientoherramienta',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_horas__isnull', True), ('intervalo_horas__gt', 0), _connector='OR'), name='plan_intervalo_horas_positivo'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['herramienta', 'estado'], name='herramienta_herrami_9c553d_idx'),
        ),
        migrations.AddConstraint(
            model_name='registromantenimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'EN_CURSO')), fields=('herramienta',), name='un_mantenimiento_en_curso_por_herramienta'),
        ),
        migrations.AddConstraint(
            model_name='registromantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('costo__isnull', True), ('costo__gte', 0), _connector='OR'), name='mantenimiento_costo_no_negativo'),
        ),
    ]
