# Generated by Django 6.1 on 2026-10-09 06:48

import apps.documentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        ('vehiculos', '0007_mantenimientovehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOAT', 'SOAT'), ('REVISION_TECNICA', 'Revisión técnica'), ('TARJETA_PROPIEDAD', 'Tarjeta de propiedad'), ('CERTIFICADO_GAS', 'Certificado de gas (GNV/GLP)'), ('LICENCIA_CONDUCIR', 'Licencia de conducir'), ('DOCUMENTO_IDENTIDAD', 'Copia de documento de identidad'), ('CONTRATO', 'Contrato / convenio'), ('OTRO', 'Otro')], db_index=True, max_length=25)),
                ('numero', models.CharField(blank=True, default='', max_length=60)),
                ('entidad_emisora', models.CharField(blank=True, default='', help_text='Aseguradora, planta de revisión, etc.', max_length=120)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, storage=apps.documentos.models.almacen_privado, upload_to=apps.documentos.models._ruta_archivo)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=200)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['fecha_vencimiento', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', True), ('vehiculo__isnull', False)), models.Q(('cliente__isnull', False), ('vehiculo__isnull', True)), _connector='OR'), name='documento_vehiculo_o_cliente')],
            },
        ),
    ]
