# Generated by Django 6.1 on 2026-08-19 21:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('estado', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], db_index=True, default='activo', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('requiere_cambio_password', models.BooleanField(default=False)),
                ('mfa_habilitado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('accion', models.CharField(db_index=True, max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.CharField(blank=True, max_length=50, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('visible_menu', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submodulos', to='seguridad.modulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('accion', models.CharField(db_index=True, max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='seguridad.modulo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['id_modulo', 'accion'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('navegador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(db_index=True, default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesiones',
                'ordering': ['-ultimo_acceso'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALLOW', 'Permitir'), ('DENY', 'Denegar')], max_length=10)),
                ('alcance', models.CharField(blank=True, choices=[('GLOBAL', 'Global — acceso total'), ('TALLER', 'Taller — solo su taller/sucursal'), ('ASIGNADO', 'Asignado — solo registros asignados a él'), ('PROPIO', 'Propio — solo los que él mismo creó')], max_length=30, null=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_permisos', to='seguridad.permiso')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Directo de Usuario',
                'verbose_name_plural': 'Permisos Directos de Usuarios',
                'db_table': 'usuario_permisos',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('GLOBAL', 'Global — acceso total'), ('TALLER', 'Taller — solo su taller/sucursal'), ('ASIGNADO', 'Asignado — solo registros asignados a él'), ('PROPIO', 'Propio — solo los que él mismo creó')], default='PROPIO', max_length=30)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'rol_permisos',
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='seguridad.rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'usuario_roles',
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
    ]
