# Generated by Django 6.1 on 2026-08-26 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_repuesto_tipo_igv'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_asignadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal de Usuario',
                'verbose_name_plural': 'Sucursales de Usuarios',
                'db_table': 'usuario_sucursales',
                'unique_together': {('id_usuario', 'sucursal')},
            },
        ),
    ]
