# Generated by Django 6.1 on 2026-08-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_usuariosucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'db_table': 'empresa',
            },
        ),
    ]
