# Generated by Django 6.1 on 2026-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_departamento_provincia_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
