# Generated by Django 6.1 on 2026-09-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_empresa_email_empresa_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta Bancaria',
                'verbose_name_plural': 'Tipos de Cuenta Bancaria',
                'db_table': 'tipos_cuenta_bancaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('cci', models.CharField(blank=True, max_length=100, null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)')], default='PEN', max_length=3)),
                ('titular', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='seguridad.tipocuentabancaria')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
                'ordering': ['banco', 'moneda'],
            },
        ),
    ]
