# Generated by Django 6.1 on 2026-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_tipocuentabancaria_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dias_validez_cotizacion',
            field=models.PositiveIntegerField(default=15, help_text='Días de validez por defecto para las cotizaciones generadas.'),
        ),
    ]
