# Generated by Django 6.1 on 2026-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_empresa_dias_validez_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='permiso_ver',
            field=models.CharField(blank=True, help_text='Código de Permiso requerido para que este módulo aparezca en el menú del usuario. Si es nulo, el módulo es visible para cualquier usuario autenticado (o, si tiene submódulos, se muestra cuando al menos un hijo es visible).', max_length=100, null=True),
        ),
    ]
