# Generated by Django 6.1 on 2026-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_modulo_permiso_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='grupo_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='grupo_submodulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
