# Generated by Django 6.1 on 2026-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_permiso_grupo_padre_permiso_grupo_submodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sunat_clave_secundaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_gre_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_gre_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_modo',
            field=models.CharField(choices=[('BETA', 'Pruebas (Beta)'), ('PRODUCCION', 'Producción')], default='BETA', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_usuario_secundario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
