# Generated by Django 6.1 on 2026-09-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0013_permiso_prometer_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Usado por la API de facturación electrónica; si está vacío se usa razón social.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubigeo',
            field=models.CharField(blank=True, help_text='Código de ubigeo INEI (6 dígitos), requerido para emitir comprobantes electrónicos.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='urbanizacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
