# Generated by Django 6.1 on 2026-08-22 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0005_almacen_direccion'),
        ('vehiculos', '0002_rename_motor_vehiculo_numero_motor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo_sunat', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'ventas_impuesto',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('requiere_referencia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'ventas_metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cajas', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'ventas_caja',
                'unique_together': {('sucursal', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_cierre_esperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_cierre_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=20)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sesiones', to='ventas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'db_table': 'ventas_sesion_caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], db_index=True, max_length=15)),
                ('concepto', models.CharField(choices=[('VENTA', 'Venta'), ('COBRO_CUOTA', 'Cobro de Cuota'), ('REPARACION', 'Servicio / Reparación'), ('INGRESO_MANUAL', 'Ingreso Manual (Ajuste)'), ('EGRESO_MANUAL', 'Egreso Manual (Gasto)')], db_index=True, max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_caja_creados', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_caja', to='ventas.metodopago')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ventas.sesioncaja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'ventas_movimiento_caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRE_VENTA', 'Pre Venta (Kiosko)'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('AL_CREDITO', 'Al Crédito'), ('ANULADA', 'Anulada')], db_index=True, default='PRE_VENTA', max_length=20)),
                ('tipo_comprobante', models.CharField(blank=True, choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('TICKET', 'Ticket de Venta'), ('NOTA_CREDITO', 'Nota de Crédito')], max_length=30, null=True)),
                ('serie_correlativo', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ticket_kiosko', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_emision', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='clientes.cliente')),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='ventas.sesioncaja')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='inventario.sucursal')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('movimiento_caja', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pago_venta_rel', to='ventas.movimientocaja')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'ventas_pago_venta',
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='despachos_venta', to='inventario.almacen')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_venta', to='inventario.repuesto')),
                ('impuesto_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_venta', to='ventas.impuesto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'ventas_detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_credito', models.CharField(db_index=True, max_length=50, unique=True)),
                ('frecuencia_pago', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=15)),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ATRASADO', 'Atrasado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_por_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'db_table': 'ventas_cuenta_cobrar',
            },
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada')], db_index=True, default='PENDIENTE', max_length=15)),
                ('cuenta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='ventas.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Cuota de Crédito',
                'verbose_name_plural': 'Cuotas de Crédito',
                'db_table': 'ventas_cuota_credito',
                'ordering': ['numero_cuota'],
                'unique_together': {('cuenta_cobrar', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('TICKET', 'Ticket de Venta'), ('NOTA_CREDITO', 'Nota de Crédito')], db_index=True, max_length=30)),
                ('serie', models.CharField(db_index=True, max_length=10)),
                ('correlativo_actual', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='series_comprobantes', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobantes',
                'db_table': 'ventas_serie_comprobante',
                'unique_together': {('sucursal', 'tipo_comprobante', 'serie')},
            },
        ),
    ]
