# Generated by Django 6.1 on 2026-08-26 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_repuesto_tipo_igv'),
        ('ventas', '0003_tipocomprobante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['id'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='seriecomprobante',
            options={'ordering': ['id'], 'verbose_name': 'Serie de Comprobante', 'verbose_name_plural': 'Series de Comprobantes'},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobantes'},
        ),
        migrations.AddField(
            model_name='caja',
            name='almacen_defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cajas_defecto', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
