# Generated by Django 6.1 on 2026-08-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_metodopago_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], db_index=True, default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
