# Generated by Django 6.1 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_monto_recibido_venta_vuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
