# Generated by Django 6.1 on 2026-08-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_add_kilometraje_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
