# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventariostock_stock_disponible_and_more'),
        ('ventas', '0008_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion_servicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_venta', to='inventario.repuesto'),
        ),
    ]
