# Generated by Django 6.1 on 2026-09-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_detalleventa_descripcion_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotacredito',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.cuotacredito')),
                ('movimiento_caja', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pago_cuota_rel', to='ventas.movimientocaja')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuota',
                'db_table': 'ventas_pago_cuota',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
