# Generated by Django 6.1 on 2026-09-03 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_cuotacredito_estado_pagocuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='operacion_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
