# Generated by Django 6.1 on 2026-09-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventariostock_stock_disponible_and_more'),
        ('ventas', '0011_pagocuota_operacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='numero_recibo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SerieDocumentoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RECIBO_INGRESO', 'Recibo de Ingreso'), ('CREDITO', 'Código de Crédito')], max_length=50)),
                ('prefijo', models.CharField(db_index=True, max_length=10)),
                ('correlativo_actual', models.IntegerField(default=0)),
                ('longitud_correlativo', models.IntegerField(default=6)),
                ('estado', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='series_internas', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Serie Interna',
                'verbose_name_plural': 'Series Internas',
                'db_table': 'ventas_serie_interna',
                'ordering': ['id'],
                'unique_together': {('sucursal', 'tipo_documento')},
            },
        ),
    ]
