# Generated by Django 6.1 on 2026-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_movimientocaja_numero_recibo_seriedocumentointerno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriedocumentointerno',
            name='tipo_documento',
            field=models.CharField(choices=[('RECIBO_INGRESO', 'Recibo de Ingreso'), ('CREDITO', 'Código de Crédito'), ('GUIA_REMISION', 'Guía de Remisión')], max_length=50),
        ),
    ]
