# Generated by Django 6.1 on 2026-09-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_seriedocumentointerno_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('OPERATIVA', 'Caja Operativa'), ('CAJA_CHICA', 'Caja Chica')], db_index=True, default='OPERATIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='estado_movimiento',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('PENDIENTE', 'Pendiente de Aprobación'), ('RECHAZADO', 'Rechazado')], db_index=True, default='APROBADO', max_length=15),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='origen_movimiento',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('COBRO', 'Cobro de Cuota'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('TRANSFERENCIA', 'Transferencia entre Cajas'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('APERTURA', 'Apertura de Caja')], db_index=True, default='AJUSTE_MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia_origen',
            field=models.CharField(blank=True, help_text='Ej: V-00125, CXP-0031', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('COBRO_CUOTA', 'Cobro de Cuota'), ('REPARACION', 'Servicio / Reparación'), ('ANTICIPO', 'Anticipo'), ('OTROS_INGRESOS', 'Otros Ingresos'), ('GASTO_OPERATIVO', 'Gasto Operativo'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('DEVOLUCION', 'Devolución'), ('RETIRO', 'Retiro'), ('OTROS_EGRESOS', 'Otros Egresos'), ('INGRESO_MANUAL', 'Ingreso Manual (Ajuste)'), ('EGRESO_MANUAL', 'Egreso Manual (Gasto)'), ('TRANSFERENCIA_SALIENTE', 'Transferencia Saliente'), ('TRANSFERENCIA_ENTRANTE', 'Transferencia Entrante')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CERRADA_CON_DIFERENCIA', 'Cerrada con Diferencia')], db_index=True, default='ABIERTA', max_length=30),
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_teorico', models.DecimalField(decimal_places=2, help_text='Calculado por el sistema', max_digits=12)),
                ('saldo_contado', models.DecimalField(decimal_places=2, help_text='Contado físicamente por el cajero', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='saldo_contado - saldo_teorico (negativo = faltante)', max_digits=12)),
                ('motivo_diferencia', models.TextField(blank=True, null=True)),
                ('es_cierre_final', models.BooleanField(default=False, help_text='True si este arqueo es el que cierra la sesión')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='ventas.sesioncaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arqueos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'cajas_arqueo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='COMPLETADA', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movimiento_entrada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencia_entrada', to='ventas.movimientocaja')),
                ('movimiento_salida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencia_salida', to='ventas.movimientocaja')),
                ('sesion_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_recibidas', to='ventas.sesioncaja')),
                ('sesion_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_enviadas', to='ventas.sesioncaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre Cajas',
                'verbose_name_plural': 'Transferencias entre Cajas',
                'db_table': 'cajas_transferencia',
                'ordering': ['-fecha'],
            },
        ),
    ]
