# Generated by Django 6.1 on 2026-09-11 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_guiaremisiondetalle_guia_remision_detalle_cantidad_positiva_and_more'),
        ('ventas', '0014_cajas_extend_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_venta_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='movimiento_caja_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='unica_sesion_abierta_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='transferenciacaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transferencia_caja_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transferenciacaja',
            constraint=models.CheckConstraint(condition=models.Q(('sesion_origen', models.F('sesion_destino')), _negated=True), name='transferencia_caja_origen_distinto_destino'),
        ),
    ]
