# Generated by Django 6.1 on 2026-09-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_detalleventa_detalle_venta_cantidad_positiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriedocumentointerno',
            name='tipo_documento',
            field=models.CharField(choices=[('RECIBO_INGRESO', 'Recibo de Ingreso'), ('CREDITO', 'Código de Crédito'), ('GUIA_REMISION', 'Guía de Remisión'), ('PROFORMA', 'Proforma / Cotización'), ('TRASLADO', 'Nota de Traslado')], max_length=50),
        ),
    ]
