# Generated by Django 6.1 on 2026-09-14 04:42

import apps.ventas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_trasladoinventario_correlativo_and_more'),
        ('ventas', '0016_alter_seriedocumentointerno_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskoTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_activacion', models.CharField(db_index=True, default=apps.ventas.models._generar_codigo_activacion, max_length=20, unique=True)),
                ('token', models.CharField(db_index=True, default=apps.ventas.models._generar_token_kiosko, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kioskos', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Kiosko',
                'verbose_name_plural': 'Kioskos',
                'db_table': 'ventas_kiosko_terminal',
                'ordering': ['sucursal__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='kiosko',
            field=models.ForeignKey(blank=True, help_text='Terminal de kiosko que generó este ticket, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.kioskoterminal'),
        ),
    ]
