# Generated by Django 6.1 on 2026-09-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_kioskoterminal_venta_kiosko'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
