# Generated by Django 6.1 on 2026-09-29 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_tipo_documento_alter_cliente_apellidos'),
        ('inventario', '0023_repuesto_visible_en_kiosko'),
        ('ventas', '0019_backfill_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ACEPTADA', 'Aceptada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada'), ('CONVERTIDA', 'Convertida a POS')], db_index=True, default='EMITIDA', max_length=20)),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('incluye_igv', models.BooleanField(default=True)),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], db_index=True, default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('convertido_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proformas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proformas_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proformas', to='inventario.sucursal')),
                ('venta_generada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_origen', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'db_table': 'ventas_proforma',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProformaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REPUESTO', 'Repuesto / Producto'), ('SERVICIO', 'Servicio')], default='REPUESTO', max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.proforma')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_proforma', to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Proforma',
                'verbose_name_plural': 'Detalles de Proforma',
                'db_table': 'ventas_proforma_detalle',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='proforma_detalle_cantidad_positiva')],
            },
        ),
    ]
