# Generated by Django 6.1 on 2026-10-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_venta_anulado_por_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='qr_descripcion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pagos_qr/'),
        ),
    ]
