# Generated by Django 6.1 on 2026-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='motor',
            new_name='numero_motor',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serie',
            new_name='numero_serie',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='vehiculos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_asientos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
