# Generated by Django 6.1 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_rename_motor_vehiculo_numero_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
