# Generated by Django 6.1 on 2026-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_add_kilometraje_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=15, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_inscripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('configuracion_vehicular', models.CharField(blank=True, max_length=50, null=True)),
                ('carga_util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehículo de Transporte',
                'verbose_name_plural': 'Vehículos de Transporte',
                'db_table': 'vehiculo_transporte',
                'ordering': ['-id'],
            },
        ),
    ]
