# Generated by Django 6.1 on 2026-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'Gasolinero'), ('PETROLEO', 'Petrolero')], max_length=10, null=True),
        ),
    ]
