# Generated by Django 6.1 on 2026-10-07 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculoqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACEITE', 'Cambio de aceite'), ('FILTRO_ACEITE', 'Filtro de aceite'), ('FILTRO_AIRE', 'Filtro de aire'), ('FILTRO_COMBUSTIBLE', 'Filtro de combustible')], max_length=25)),
                ('fecha_realizado', models.DateField()),
                ('kilometraje_realizado', models.PositiveIntegerField()),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'vehiculo_mantenimiento',
                'ordering': ['-fecha_realizado', '-id'],
                'constraints': [
                    models.CheckConstraint(condition=(models.Q(intervalo_km__isnull=False, intervalo_km__gt=0) | models.Q(intervalo_meses__isnull=False, intervalo_meses__gt=0)), name='mantenimiento_intervalo_requerido'),
                    models.CheckConstraint(condition=models.Q(intervalo_km__isnull=True) | models.Q(intervalo_km__gt=0), name='mantenimiento_km_positivo'),
                    models.CheckConstraint(condition=models.Q(intervalo_meses__isnull=True) | models.Q(intervalo_meses__gt=0), name='mantenimiento_meses_positivo'),
                ],
            },
        ),
    ]
